/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/questionario/DetalharQuestionario': RouteRecordInfo<'/questionario/DetalharQuestionario', '/questionario/DetalharQuestionario', Record<never, never>, Record<never, never>>,
    '/questionario/HomeQuestionario': RouteRecordInfo<'/questionario/HomeQuestionario', '/questionario/HomeQuestionario', Record<never, never>, Record<never, never>>,
    '/questionario/IncluirQuestionario': RouteRecordInfo<'/questionario/IncluirQuestionario', '/questionario/IncluirQuestionario', Record<never, never>, Record<never, never>>,
  }
}
